using System.Collections.Immutable;
using System.Runtime.CompilerServices;
using Microsoft.CodeAnalysis;
using SourceGeneratorTestHelpers.Common;

namespace SourceGeneratorTestHelpers.MSTest;

public abstract class GeneratorDriverTestBase : VerifyBase
{
    /// <summary>Verifies that the generated source from a <see cref="GeneratorDriverRunResult"/> with a specific file path ending matches the expected source.</summary>
    /// <param name="result">The <see cref="GeneratorDriverRunResult"/> to get the source from.</param>
    /// <param name="filePathEndsWith">The string that the generated source's file path should end with.</param>
    /// <param name="expectedSource">The expected source that the generated source should match.</param>
    /// <exception cref="ArgumentNullException">If <paramref name="result"/> is null.</exception>
    public static void ShouldProduce(GeneratorDriverRunResult result, string filePathEndsWith, string expectedSource)
    {
        ArgumentNullException.ThrowIfNull(result);

        result.InternalShouldProduce(filePathEndsWith, expectedSource, false, false, _ => { });
    }

    /// <summary>Verifies that the generated source from a <see cref="GeneratorDriverRunResult"/> with a specific file path ending matches the expected source.</summary>
    /// <param name="result">The <see cref="GeneratorDriverRunResult"/> to get the source from.</param>
    /// <param name="filePathEndsWith">The string that the generated source's file path should end with.</param>
    /// <param name="expectedSource">The expected source that the generated source should match.</param>
    /// <param name="assertOnErrors"><see langword="true"/> to assert on reported errors, <see langword="false"/> othwerwise. Defaults to <see langword="true"/>.</param>
    /// <param name="assertOnWarnings"><see langword="true"/> to assert on reported warnings, <see langword="false"/> othwerwise. Defaults to <see langword="false"/>.</param>
    /// <exception cref="ArgumentNullException">If <paramref name="result"/> is null.</exception>
    public static void ShouldProduce(
        (ImmutableArray<Diagnostic> CompilationDiagnostics, GeneratorDriverRunResult Result) result,
        string filePathEndsWith,
        string expectedSource,
        bool assertOnErrors = true,
        bool assertOnWarnings = false
    )
    {
        ArgumentNullException.ThrowIfNull(result.Result);

        result.CompilationDiagnostics.InternalAssertOnDiagnostics(assertOnErrors, assertOnWarnings, message => throw new AssertFailedException(message),
            "There were errors in the compilation."
        );
        result.Result.Diagnostics.InternalAssertOnDiagnostics(assertOnErrors, assertOnWarnings, message => throw new AssertFailedException(message),
            "There were errors in the output generated by the source generator."
        );

        result.Result.InternalShouldProduce(filePathEndsWith, expectedSource, assertOnErrors, assertOnWarnings,
            message => throw new AssertFailedException(message)
        );
    }

    /// <summary>Verifies that the generated source from a <see cref="GeneratorDriverRunResult"/> with a specific file path using <see cref="VerifyBase.Verify(string?, string, VerifySettings?, string)"/>.</summary>
    /// <param name="result">The <see cref="GeneratorDriverRunResult"/> to get the source from.</param>
    /// <param name="filePathEndsWith">The string that the generated source's file path should end with.</param>
    /// <param name="verifySettings">The verify settings.</param>
    /// <param name="sourceFile">The source file.</param>
    /// <exception cref="ArgumentNullException">If <paramref name="result"/> is null.</exception>
    public SettingsTask VerifyAsync(
        GeneratorDriverRunResult result,
        string filePathEndsWith,
        VerifySettings? verifySettings = null,
        [CallerFilePath] string sourceFile = ""
    )
    {
        ArgumentNullException.ThrowIfNull(result);

        var generatedSource = result.InternalGetSource(filePathEndsWith);
        var source = generatedSource.HasValue ? generatedSource.Value.Source.ReplaceLineEndings("\n") : "";

        // ReSharper disable once ExplicitCallerInfoArgument
        return VerifySource(source, verifySettings, sourceFile);
    }

    /// <summary>Verifies that the generated source from a <see cref="GeneratorDriverRunResult"/> with a specific file path using <see cref="VerifyBase.Verify(string?, string, VerifySettings?, string)"/>.</summary>
    /// <param name="result">The <see cref="GeneratorDriverRunResult"/> to get the source from.</param>
    /// <param name="filePathEndsWith">The string that the generated source's file path should end with.</param>
    /// <param name="snapshotName">The stable snapshot file name to use.</param>
    /// <param name="verifySettings">The verify settings.</param>
    /// <param name="sourceFile">The source file.</param>
    /// <exception cref="ArgumentNullException">If <paramref name="result"/> is null.</exception>
    /// <exception cref="ArgumentException">If <paramref name="snapshotName"/> is null or whitespace.</exception>
    public SettingsTask VerifyAsync(
        GeneratorDriverRunResult result,
        string filePathEndsWith,
        string snapshotName,
        VerifySettings? verifySettings = null,
        [CallerFilePath] string sourceFile = ""
    )
    {
        ArgumentNullException.ThrowIfNull(result);
        ArgumentException.ThrowIfNullOrWhiteSpace(snapshotName);

        var generatedSource = result.InternalGetSource(filePathEndsWith);
        var source = generatedSource.HasValue ? generatedSource.Value.Source.ReplaceLineEndings("\n") : "";

        // ReSharper disable once ExplicitCallerInfoArgument
        return VerifySource(source, verifySettings, sourceFile, snapshotName);
    }

    /// <summary>Verifies that the generated source from a <see cref="GeneratorDriverRunResult"/> with a specific file path using <see cref="VerifyBase.Verify(string?, string, VerifySettings?, string)"/>.</summary>
    /// <param name="result">The <see cref="GeneratorDriverRunResult"/> to get the source from.</param>
    /// <param name="filePathEndsWith">The string that the generated source's file path should end with.</param>
    /// <param name="assertOnErrors"><see langword="true"/> to assert on reported errors, <see langword="false"/> othwerwise. Defaults to <see langword="true"/>.</param>
    /// <param name="assertOnWarnings"><see langword="true"/> to assert on reported warnings, <see langword="false"/> othwerwise. Defaults to <see langword="false"/>.</param>
    /// <param name="verifySettings">The verify settings.</param>
    /// <param name="sourceFile">The source file.</param>
    /// <exception cref="ArgumentNullException">If <paramref name="result"/> is null.</exception>
    public SettingsTask VerifyAsync(
        (ImmutableArray<Diagnostic> CompilationDiagnostics, GeneratorDriverRunResult Result) result,
        string filePathEndsWith,
        bool assertOnErrors = true,
        bool assertOnWarnings = false,
        VerifySettings? verifySettings = null,
        [CallerFilePath] string sourceFile = ""
    )
    {
        ArgumentNullException.ThrowIfNull(result.Result);

        result.CompilationDiagnostics.InternalAssertOnDiagnostics(assertOnErrors, assertOnWarnings, message => throw new AssertFailedException(message),
            "There were errors in the compilation."
        );
        result.Result.Diagnostics.InternalAssertOnDiagnostics(assertOnErrors, assertOnWarnings, message => throw new AssertFailedException(message),
            "There were errors in the output generated by the source generator."
        );

        var generatedSource = result.Result.InternalGetSource(filePathEndsWith);
        var source = generatedSource.HasValue ? generatedSource.Value.Source.ReplaceLineEndings("\n") : "";

        // ReSharper disable once ExplicitCallerInfoArgument
        return VerifySource(source, verifySettings, sourceFile);
    }

    /// <summary>Verifies that the generated source from a <see cref="GeneratorDriverRunResult"/> with a specific file path using <see cref="VerifyBase.Verify(string?, string, VerifySettings?, string)"/>.</summary>
    /// <param name="result">The <see cref="GeneratorDriverRunResult"/> to get the source from.</param>
    /// <param name="filePathEndsWith">The string that the generated source's file path should end with.</param>
    /// <param name="snapshotName">The stable snapshot file name to use.</param>
    /// <param name="assertOnErrors"><see langword="true"/> to assert on reported errors, <see langword="false"/> othwerwise. Defaults to <see langword="true"/>.</param>
    /// <param name="assertOnWarnings"><see langword="true"/> to assert on reported warnings, <see langword="false"/> othwerwise. Defaults to <see langword="false"/>.</param>
    /// <param name="verifySettings">The verify settings.</param>
    /// <param name="sourceFile">The source file.</param>
    /// <exception cref="ArgumentNullException">If <paramref name="result"/> is null.</exception>
    /// <exception cref="ArgumentException">If <paramref name="snapshotName"/> is null or whitespace.</exception>
    public SettingsTask VerifyAsync(
        (ImmutableArray<Diagnostic> CompilationDiagnostics, GeneratorDriverRunResult Result) result,
        string filePathEndsWith,
        string snapshotName,
        bool assertOnErrors = true,
        bool assertOnWarnings = false,
        VerifySettings? verifySettings = null,
        [CallerFilePath] string sourceFile = ""
    )
    {
        ArgumentNullException.ThrowIfNull(result.Result);
        ArgumentException.ThrowIfNullOrWhiteSpace(snapshotName);

        result.CompilationDiagnostics.InternalAssertOnDiagnostics(assertOnErrors, assertOnWarnings, message => throw new AssertFailedException(message),
            "There were errors in the compilation."
        );
        result.Result.Diagnostics.InternalAssertOnDiagnostics(assertOnErrors, assertOnWarnings, message => throw new AssertFailedException(message),
            "There were errors in the output generated by the source generator."
        );

        var generatedSource = result.Result.InternalGetSource(filePathEndsWith);
        var source = generatedSource.HasValue ? generatedSource.Value.Source.ReplaceLineEndings("\n") : "";

        // ReSharper disable once ExplicitCallerInfoArgument
        return VerifySource(source, verifySettings, sourceFile, snapshotName);
    }

    private SettingsTask VerifySource(string source, VerifySettings? verifySettings, string sourceFile, string? snapshotName = null)
    {
        var task = Verify(source, "txt", verifySettings, sourceFile);
        return snapshotName is null ? task : task.UseFileName(snapshotName);
    }
}
